// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGBPrjWicyeDIMmdzHU6IWk9innR_sNs',
    appId: '1:554520968396:web:0dc84ca9c9d92b380b9669',
    messagingSenderId: '554520968396',
    projectId: 'apiexample-9dc23',
    authDomain: 'apiexample-9dc23.firebaseapp.com',
    storageBucket: 'apiexample-9dc23.appspot.com',
    measurementId: 'G-WGXDG8DQ9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXnugygTLUOmZ0ZmY6F8ZibUbJcO8iv4',
    appId: '1:554520968396:android:a4f5681923b9945a0b9669',
    messagingSenderId: '554520968396',
    projectId: 'apiexample-9dc23',
    storageBucket: 'apiexample-9dc23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg9iClAfWrUMBrh3iEj2U71WgOfmQ73iI',
    appId: '1:554520968396:ios:5fa31afe3e06347c0b9669',
    messagingSenderId: '554520968396',
    projectId: 'apiexample-9dc23',
    storageBucket: 'apiexample-9dc23.appspot.com',
    iosBundleId: 'com.example.apiexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg9iClAfWrUMBrh3iEj2U71WgOfmQ73iI',
    appId: '1:554520968396:ios:6951e29c53332f240b9669',
    messagingSenderId: '554520968396',
    projectId: 'apiexample-9dc23',
    storageBucket: 'apiexample-9dc23.appspot.com',
    iosBundleId: 'com.example.apiexample.RunnerTests',
  );
}
